### PR TITLE
Laravel 5.3 Package Shift

### PR DESCRIPTION
**Pull request by laravel-shift**
This pull request includes the changes for upgrading your Laravel Package to Laravel 5.3. Feel free to commit any additional changes to the `laravel-package-5.3-shift` branch.

**Before merging**, you should:

- Checkout the `laravel-package-5.3-shift` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your code

This Shift is still in *beta*. If there were changes you feel could have been automated, please leave a comment on this pull request to help improve [Laravel Shift](https://laravelshift.com).

### CODE REVIEW

**Comment by laravel-shift** [comment]
⚠ The default behavior of `Route::resource()` changed in Laravel 5.3. All resource route parameters are now singularized by default and URL prefixes no longer affect the route names.You should review your resource routes and verify this singularized naming will not affect your parameters (or if you were doing this manually, you can remove the `parameter`). In addition, verify you are no longer appending the URI prefix to the route name.

Found `Route::resource()` in:

- [ ] routes/web.php

**Comment by laravel-shift** [comment]
❌ Laravel 5.3 requires PHP 5.6.4+. You have an existing dependency for PHP in your `composer.json`. Ensure it meets the new version requirement of `>=5.6.4`.

**Comment by laravel-shift** [comment]
❌ Laravel 5.3 `where` performs a "loose" comparison. In addition, the *strict* parameter was removed. If you need to perform a "strict" comparison, you can use `whereStrict` instead.

You should review the following usages of `where` to ensure you do not require "strict" compaison:

- [ ] app/Repositories/Task/TaskRepository.php
- [ ] app/Repositories/Lead/LeadRepository.php
- [ ] app/Models/Tasks.php
- [ ] app/Models/User.php
- [ ] app/Models/Leads.php
- [ ] app/Models/Integration.php
- [ ] app/Http/Controllers/IntegrationsController.php
- [ ] app/Http/Controllers/TasksController.php
- [ ] app/Http/Controllers/UsersController.php
- [ ] app/Http/Controllers/NotificationsController.php
- [ ] app/Http/Controllers/LeadsController.php

**Comment by laravel-shift** [comment]
❌ In Laravel 5.3, the `JoinClause` class has been rewritten to unify its syntax with the query builder. The optional `$where` parameter of the `on` clause and the `bindings` property have been removed.

You should review the following usages of `join` to ensure you're not using these features:

- [ ] app/Repositories/User/UserRepository.php

**Comment by laravel-shift** [comment]
❌ The Query Builder returns collections, instead of plain arrays, in Laravel 5.3. You will need to upgrade your code to use collections or chain the `all()` method onto your query to return a plain array.

You should review the following usages of Query Builder:

- [ ] app/Repositories/Task/TaskRepository.php
- [ ] app/Repositories/User/UserRepository.php
- [ ] app/Repositories/Lead/LeadRepository.php
- [ ] database/seeds/UsersTableSeeder.php
- [ ] database/seeds/DepartmentsTableSeeder.php
- [ ] database/seeds/IndustriesTableSeeder.php
- [ ] database/seeds/LeadsTableSeeder.php
- [ ] database/seeds/SettingsTableSeeder.php
- [ ] database/seeds/UsersDummyTableSeeder.php
- [ ] database/migrations/2016_01_18_113656_create_leads_table.php
- [ ] database/migrations/2014_10_12_000000_create_users_table.php
- [ ] database/migrations/2016_01_10_204413_create_comments_table.php
- [ ] database/migrations/2016_01_18_202853_create_notes_table.php
- [ ] database/migrations/2015_12_29_204031_tasks_table.php
- [ ] database/migrations/2016_03_21_172416_create_department_user_table.php
- [ ] database/migrations/2016_01_26_003903_documents.php
- [ ] database/migrations/2015_12_28_163028_create_clients_table.php

**Comment by laravel-shift** [comment]
@Bottelet It seems you used the Laravel Pacakage Shift even though this is a Laravel app. You'll the Laravel 5.3 Shift does a better job.

**Comment by Bottelet** [comment]
@laravel-shift Yeah, I realised that. :smile:

**Pull request merged**
