### PR TITLE
Add docker for development

### PR DESCRIPTION
**Pull request by saleh199**
Add support for docker during development

### CODE REVIEW

**Comment by Bottelet** [comment]
@saleh199 I have never really used Docker myself in production. I'm not sure if i like that docker is gonna be a requirement. But I'll take a look through what is done, and see if we can't fit it in... As i do like the thought of "supporting" Docker. Thanks for the PR!

**Comment by saleh199** [comment]
I made this for development only not for production, and it's very useful.
You can use it like vagrant (Homestead).

**Comment by Bottelet** [comment]
But, as i see it, it's not gonna be required to have docker to install the crm, so I think, that the readme should be re-written a bit to have it's own chapter including how to install Flarepoint with Docker, and a chapter how to do it without Docker, or maybe in the wiki (Could be a good reason to start the wiki, been thinking of it for some time now :)) Or am i off there?

**Comment by saleh199** [comment]
Yes, It's good we can use wiki for making something about docker, and I'll take care of it cause I prefer to use docker instead of vagrant or local server :), So I'll revert readme.md to prev version and start with wiki.

**Comment by Bottelet** [comment]
Very nice! 👍

**Comment by saleh199** [comment]
@Bottelet I can't write wiki for project, could you please give me permission to write it.
Thanks

**Comment by Bottelet** [comment]
There you go @saleh199 You should have gotten an invite.

**Comment by saleh199** [comment]
@Bottelet It's ready https://github.com/Bottelet/Flarepoint-crm/wiki/Using-Docker

**Comment by Bottelet** [comment]
👍  Thank you!

**Pull request merged**
